### PR TITLE
Removed Flot.js library

### PR DESCRIPTION
**Pull request by miniche**
The flot library (http://www.flotcharts.org/) is not used anymore.
I think we will debate about a new graph library in a next release, when we will refactor the internal web server.

This pull request deletes also an old template file (dashboard_mac.tpl), not used since the version 0.1.0.

### CODE REVIEW

**Comment by miniche** [comment]
Hey guys! Ready for your comments and your review ;-)

**Comment by Ninir** [comment]
Here is a list of libraries we should have a look to:
- http://www.chartjs.org/  (even working on IE7/8 with polyfills)
- http://d3js.org/

**Comment by Ninir** [comment]
:+1:

**Comment by Guimove** [comment]
:+1:

**Pull request merged**
