### PR TITLE
Release 0.4.0

### PR DESCRIPTION
**Pull request by miniche**
This pull request is dedicated to releasing the version 0.4.0.

This version is a minor but important improvement. It contains:
## Improvement
- [x] #88: New host module and fixed memory collector for OS X 10.9 Mavericks.

---
## Remains to be done:
- [x] Update the version number in the Config module
- [x] Write the release notes into the official documentation
- [x] Update the release date in the NEWS file

### CODE REVIEW

**Comment by miniche** [comment]
I have written the release note for this version: http://docs.centralreport.net/unix-agent/releases/0.4.0

**Comment by miniche** [comment]
Good for me. All features had been tested in the pull request #88.

Can be merged tonight? :smile:

**Comment by Ninir** [comment]
:+1:

**Comment by miniche** [comment]
Packages has been generated for the online installer/uninstaller (you can read the [official documentation](http://docs.centralreport.net/unix-agent/install) to know more about this feature).

**Pull request merged**
