### PR TITLE
[WIP] Documentations and scripts comment

### PR DESCRIPTION
**Pull request by miniche**
Updating readme.md for Github and comments at the beginning of each scripts.

### CODE REVIEW

**Comment by Ninir** [comment]
@miniche Was it ready to be merged? if yes, please update your PR title to remove the WIP flag, otherwise it is confusing. If not, @Guimove please stop merging everything :)

**Comment by miniche** [comment]
Not at all. When @Guimove merged his branch with "develop", it seems "develop-doc" was merged too...
Strange.

Network graph is confusing when you look at the end. @Guimove has created his branch from "develop-doc", the pull request has been validated because all my commits was included in "api-routes", no ?

**Comment by Ninir** [comment]
Mmm, the diff is clearly weird yeah.. it seems you took the api_route commits into your branch, that's weird.

@miniche By the way, why keeping a bad master branch? why not having a master which is the main branch?

I can make a tag (you can call that a snapshot) of master and then merge everything into master, so that we'll still have the master branch, or I can at least do a copy of master, into an other branch (old-master), and then move everything from develop into master.

**Comment by Ninir** [comment]
And I will revert changes in master so that you will be able to re-open your Pull Request and continue your work on it :)

**Comment by Guimove** [comment]
Woaaw I only merged "Api Route"

**Comment by miniche** [comment]
All right, master is very dirty.

In one or two weeks, I think we will able to release a first alpha version. It will be the good time to clean master by merging develop and create the first tag (the famous 0.1.0 :+1: ).

**Pull request merged**
